// tableau d’objets recettes
const recettes = [
    {
      id: 1,
      titre: "Tarte aux pommes",
      description: "Une délicieuse tarte faite maison.",
      image: "Img/image.png",
      alt: "Tarte aux pommes",
      date: new Date().toLocaleString(),
    },
    {
      id: 2,
      titre: "Gratin dauphinois",
      description: "Un classique de la cuisine française.",
      image: "Img/image.png",
      alt: "Gratin dauphinois",
      date: new Date().toLocaleString(),
    },
    {
      id: 3,
      titre: "Crêpes sucrées",
      description: "Des crêpes légères et savoureuses.",
      image: "Img/image.png",
      alt: "Crêpes sucrées",
      date: new Date().toLocaleString(),
    },
    {
      id: 4,
      titre: "Soupe à l'oignon",
      description: "Une soupe traditionnelle gratinée au four.",
      image: "Img/image.png",
      alt: "Soupe à l'oignon",
      date: new Date().toLocaleString(),
    },
    {
      id: 5,
      titre: "Boeuf bourguignon",
      description: "Un plat mijoté plein de saveurs.",
      image: "Img/image.png",
      alt: "Boeuf bourguignon",
      date: new Date().toLocaleString(),
    },
    {
      id: 6,
      titre: "Ratatouille",
      description: "Des légumes du soleil cuits à la perfection.",
      image: "Img/image.png",
      alt: "Ratatouille",
      date: new Date().toLocaleString(),
    },
    {
      id: 7,
      titre: "Tarte au citron",
      description: "Une tarte acidulée avec une meringue légère.",
      image: "Img/image.png",
      alt: "Tarte au citron",
      date: new Date().toLocaleString(),
    },
    {
      id: 8,
      titre: "Mousse au chocolat",
      description: "Une mousse onctueuse au chocolat noir.",
      image: "Img/image.png",
      alt: "Mousse au chocolat",
      date: new Date().toLocaleString(),
    },
    {
      id: 9,
      titre: "Quiche lorraine",
      description: "Une quiche classique au lard et fromage.",
      image: "Img/image.png",
      alt: "Quiche lorraine",
      date: new Date().toLocaleString(),
    },
    {
      id: 10,
      titre: "Salade niçoise",
      description: "Une salade fraîche avec des légumes du sud.",
      image: "Img/image.png",
      alt: "Salade niçoise",
      date: new Date().toLocaleString(),
    },
    {
      id: 11,
      titre: "Poulet basquaise",
      description: "Un plat aux saveurs du Pays basque.",
      image: "Img/image.png",
      alt: "Poulet basquaise",
      date: new Date().toLocaleString(),
    },
    {
      id: 12,
      titre: "Tajine de poulet",
      description: "Un plat marocain aux épices douces.",
      image: "Img/image.png",
      alt: "Tajine de poulet",
      date: new Date().toLocaleString(),
    },
]


